In [1]:
import numpy as np
import math
from scipy.stats import mode

In [2]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

In [3]:
from sklearn.metrics import accuracy_score

In [4]:
from numpy.random import randint

In [5]:
X=iris_dataset.data
Y=iris_dataset.target


In [6]:
#test train splitting
train=list(set(randint(0,150,150)))
test=[i for i in range(150) if i not in train]
X_train=X[train]
Y_train=Y[train]
X_test=X[test]
Y_test=Y[test]
len(train)

93

In [7]:
test_classify={}
k=11
for t in range(len(test)-1):
    A=X_test[t]
    d={}
    for i in range(len(train)-1):
        d[i]=math.dist(X_train[i],A)
    classify=[]
    for i in range(iris_dataset.target_names.shape[0]):
        classify.append(0)
    for i,s_index in zip(range(k),sorted(d,key=lambda x:d[x])):
        classify[Y_train[s_index]]=classify[Y_train[s_index]]+1
    test_classify[t]=classify.index(np.max(classify))
obs=0
for y,v in zip(Y_test,test_classify.values()):     
    if y==v:
        obs=obs+1
accuracy=1-((len(test)-obs)/len(test))
print("RESULTS:")
for data,cls in zip (X_test,test_classify.values()):
    print(data,iris_dataset.target_names[cls])
print("\nACCURACY=",accuracy)

RESULTS:
[5.  3.6 1.4 0.2] setosa
[5.  3.4 1.5 0.2] setosa
[4.4 2.9 1.4 0.2] setosa
[5.4 3.7 1.5 0.2] setosa
[4.8 3.4 1.6 0.2] setosa
[5.4 3.9 1.3 0.4] setosa
[5.1 3.7 1.5 0.4] setosa
[5.2 3.5 1.5 0.2] setosa
[5.2 3.4 1.4 0.2] setosa
[4.7 3.2 1.6 0.2] setosa
[4.8 3.1 1.6 0.2] setosa
[5.4 3.4 1.5 0.4] setosa
[5.2 4.1 1.5 0.1] setosa
[4.9 3.6 1.4 0.1] setosa
[4.4 3.  1.3 0.2] setosa
[5.1 3.4 1.5 0.2] setosa
[4.4 3.2 1.3 0.2] setosa
[5.  3.3 1.4 0.2] setosa
[7.  3.2 4.7 1.4] versicolor
[6.4 3.2 4.5 1.5] versicolor
[5.2 2.7 3.9 1.4] versicolor
[5.  2.  3.5 1. ] versicolor
[6.  2.2 4.  1. ] versicolor
[6.1 2.9 4.7 1.4] versicolor
[5.6 2.5 3.9 1.1] versicolor
[6.1 2.8 4.  1.3] versicolor
[6.3 2.5 4.9 1.5] versicolor
[6.1 2.8 4.7 1.2] versicolor
[5.7 2.6 3.5 1. ] versicolor
[5.5 2.4 3.8 1.1] versicolor
[5.5 2.4 3.7 1. ] versicolor
[6.  3.4 4.5 1.6] versicolor
[6.7 3.1 4.7 1.5] versicolor
[6.3 2.3 4.4 1.3] versicolor
[6.1 3.  4.6 1.4] versicolor
[5.8 2.6 4.  1.2] versicolor
[6.2 2.9 4.3 1.3] v